<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>GreenHypercube.Desk</RootNamespace>
    <ApplicationTitle>Green Hypercube</ApplicationTitle>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GreenHypercube\GreenHypercube.csproj" />
  </ItemGroup>
</Project>
